### PR TITLE
Pre alpha pass for milestone 3

### PR DESCRIPTION
**Pull request by Verticalfile30**
Code has been prepared for stage pre-alpha3, debuggers have been created and kernel development may begin, Bifrost 0.1.0 has been depreciated in favor for 1.0.0

### CODE REVIEW

**Comment by verticalAdmin30** [comment]
why is commit "ddd" unverified?@Verticalfile30

**Review by verticalAdmin30 — CHANGES_REQUESTED** [review]
please verify commit "ddd" or send confirmation that it was your commit

**Comment by Verticalfile30** [comment]
Oh yes, that was me, do not worry

**Comment by verticalAdmin30** [comment]
please verify by providing gpg key in armored format

**Review by verticalAdmin30 — APPROVED** [review]
signed commits certified, proceed.

**Pull request merged**
